# Training Configuration for Wall-X Robotic Multi-Modal Learning
# This configuration supports multi-modal learning with vision, language, and action data

# Model and paths configuration
log_name: "wall-oss freeze_vlm lr1e-5 batch2 grad16"
log_project: "wall_oss_libero"
model_type: wall-oss
pretrained_wallx_path: "/root/gpufree-data/models/x-square-robot/wall-oss-flow-v0.1/"  # Must set
processor_path: "/root/gpufree-data/models/x-square-robot/wall-oss-flow-v0.1/"
save_path: "/root/gpufree-data/output/train/libero_all/ckpt/"                # Must set
use_fast_tokenizer: False                       # True: train FAST, False: train Flow
action_tokenizer_path: "/path/to/fast/"         # Must set if use_fast_tokenizer is true

# Torch Profile
profile: False
profile_save_path: /path/to/profile/
profile_wait_iters: 10
profile_warmup_iters: 5
profile_active_iters: 2

# Training hyperparameters
num_warmup_steps: 100
num_training_steps: 20
learning_rate: 0.00005
min_lr: 0.00001
num_epoch: 100
gradient_accumulation_steps: 1
batch_size_per_gpu: 1
padding_side: left
epoch_save_interval: 1
val_interval: 500  # Validate every 1000 iterations

# freeze_vlm: true

# # LoRA configuration
# use_lora: false
# lora_r: 32
# lora_alpha: 32
# lora_dropout: 0.2
# lora_target_modules:
#   - "embed_tokens"
#   - "self_attn.q_proj_experts.0"
#   - "self_attn.v_proj_experts.0"
#   - "self_attn.q_proj_experts.1"
#   - "self_attn.v_proj_experts.1"
#   - "self_attn.k_proj_experts.0"
#   - "self_attn.k_proj_experts.1"
#   - "self_attn.o_proj_experts.0"
#   - "self_attn.o_proj_experts.1"
#   - "moe.experts.0.gate_proj"
#   - "moe.experts.0.up_proj"
#   - "moe.experts.0.down_proj"
#   - "moe.experts.1.gate_proj"
#   - "moe.experts.1.up_proj"
#   - "moe.experts.1.down_proj"
#   - "lm_head"
#   - "action_preprocessor.propri_proj"
#   - "action_preprocessor.w1"
#   - "action_preprocessor.w2"
#   - "action_preprocessor.w3"
#   - "action_preprocessor.action_proj_back"


# LoRA configuration
use_lora: true
lora_r: 8
lora_alpha: 24
lora_dropout: 0.1
lora_target_modules:
  - "k_proj_experts.0"
  - "v_proj_experts.0"
  - "o_proj_experts.0"
  - "q_proj_experts.1"
  - "k_proj_experts.1"
  - "v_proj_experts.1"
  - "o_proj_experts.1"
  - "gate_proj"
  - "up_proj"
  - "down_proj"

# Training optimization settings
FSDP2: false
torch_compile: false # 这个不能为true，貌似跟lora会有冲突，加载模型时key找不到

# Robot configuration - Define degrees of freedom for each component
dof_config:
  master_right_ee_cartesian_pos: 3
  master_right_ee_rotation: 3
  master_right_gripper: 1

# Agent proprioception configuration (typically matches DOF config)
agent_pos_config:
  follow_right_ee_cartesian_pos: 3
  follow_right_ee_rotation: 3
  follow_right_gripper: 1

# Checkpoint resuming configuration
# resume:
#   ckpt: "/root/gpufree-data/output/train/libero_all/ckpt/0"
#   # load_ckpt_only: true

norm_stats_path: "/root/gpufree-data/output/train/libero_all/action_stats/all_robots_action_stats.json"

enable_customized_robot_config: true
customized_robot_config:
  name: "libero_all"
  customized_dof_config:
    "action_all": 7
  customized_agent_pos_config:
    "state_all": 7

# Data configuration
data:
  use_lerobot: true

  # LeRobot dataset configuration
  lerobot_config:
    repo_id: "x-square-robot/libero_all"
    root: "/root/gpufree-data/datasets/x-square-robot/libero_all"
    episodes: null
    image_transforms: null
    delta_timestamps: null
    tolerance_s: 1e-4
    revision: null
    force_cache_sync: false
    download_videos: true
    video_backend: null

  action_horizon: 10
  train_test_split: 0.001

  # Action keys for observation and prediction
  obs_action_keys:
    - follow_right_ee_cartesian_pos
    - follow_right_ee_rotation
    - follow_right_gripper

  predict_action_keys:
    - master_right_ee_cartesian_pos
    - master_right_ee_rotation
    - master_right_gripper

  # Image resolution configuration for different camera views
  resolution:
    face_view: 224
    left_wrist_view: 224
    right_wrist_view: 224
    move1_view: 224
    move2_view: 224
    top_view: 224
    wall_view: 224
    multi_modal: 224

